//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopters
    {
        public int AdopterID { get; set; }
        public string NameAdopter { get; set; }
        public string SurnameAdopter { get; set; }
        public string MiddlenameAdopter { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string AddressAdopter { get; set; }
        public Nullable<System.DateTime> AdoptionDate { get; set; }
        public Nullable<int> ID_Dog { get; set; }
    
        public virtual Dogs Dogs { get; set; }
    }
}
