//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogs()
        {
            this.Adopters = new HashSet<Adopters>();
        }
    
        public int Dog_ID { get; set; }
        public string NameDog { get; set; }
        public string Breed { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Size { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string IsAdopted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adopters> Adopters { get; set; }
    }
}
